// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyProjectTemplate.API.Data;

#nullable disable

namespace MyProjectTemplate.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("NOCASE")
                .HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("MyProjectTemplate.API.Models.SubAlarmsDatum", b =>
                {
                    b.Property<int>("AlarmId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("AlarmID");

                    b.Property<string>("AlarmName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClearedAt")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("RaisedAt")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SeverityLevel")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SubId")
                        .HasColumnType("TEXT")
                        .HasColumnName("SubID");

                    b.HasKey("AlarmId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "SubId" }, "SubID");

                    b.ToTable("sub_alarms_data", (string)null);
                });

            modelBuilder.Entity("MyProjectTemplate.API.Models.SubControlDatum", b =>
                {
                    b.Property<Guid>("SubId")
                        .HasColumnType("TEXT")
                        .HasColumnName("SubID");

                    b.Property<string>("TimeData")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<double>("BallastState")
                        .HasColumnType("REAL");

                    b.Property<double>("PropellerState")
                        .HasColumnType("REAL");

                    b.Property<double>("RudderState")
                        .HasColumnType("REAL");

                    b.Property<double>("SternPlateState")
                        .HasColumnType("REAL");

                    b.HasKey("SubId", "TimeData")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.ToTable("sub_control_data", (string)null);
                });

            modelBuilder.Entity("MyProjectTemplate.API.Models.SubDatum", b =>
                {
                    b.Property<Guid>("SubId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("SubID");

                    b.Property<string>("SubName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("SubId")
                        .HasName("PRIMARY");

                    b.ToTable("sub_data", (string)null);
                });

            modelBuilder.Entity("MyProjectTemplate.API.Models.SubLifeSupportDatum", b =>
                {
                    b.Property<Guid>("SubId")
                        .HasColumnType("TEXT")
                        .HasColumnName("SubID");

                    b.Property<string>("TimeData")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<double?>("AirTanklevel")
                        .HasColumnType("REAL");

                    b.Property<double?>("Co2level")
                        .HasColumnType("REAL")
                        .HasColumnName("CO2Level");

                    b.Property<double?>("ExternalPressure")
                        .HasColumnType("REAL");

                    b.Property<double?>("Humidity")
                        .HasColumnType("REAL");

                    b.Property<double?>("InternalPressure")
                        .HasColumnType("REAL");

                    b.Property<double?>("O2level")
                        .HasColumnType("REAL")
                        .HasColumnName("O2Level");

                    b.Property<double?>("Temperature")
                        .HasColumnType("REAL");

                    b.HasKey("SubId", "TimeData")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.ToTable("sub_life_support_data", (string)null);
                });

            modelBuilder.Entity("MyProjectTemplate.API.Models.SubLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("LogID");

                    b.Property<string>("Level")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PerformedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SubId")
                        .HasColumnType("TEXT")
                        .HasColumnName("SubID");

                    b.Property<string>("TimeData")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("LogId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "SubId" }, "SubID")
                        .HasDatabaseName("SubID1");

                    b.ToTable("sub_logs", (string)null);
                });

            modelBuilder.Entity("MyProjectTemplate.API.Models.SubPositionDatum", b =>
                {
                    b.Property<Guid>("SubId")
                        .HasColumnType("TEXT")
                        .HasColumnName("SubID");

                    b.Property<string>("TimeData")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.HasKey("SubId", "TimeData")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.ToTable("sub_position_data", (string)null);
                });

            modelBuilder.Entity("MyProjectTemplate.API.Models.SubReactorDatum", b =>
                {
                    b.Property<int>("ReactorId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ReactorID");

                    b.Property<double?>("CoolantLevel")
                        .HasColumnType("REAL");

                    b.Property<double?>("FuelRodStatus")
                        .HasColumnType("REAL");

                    b.Property<double?>("Radiation")
                        .HasColumnType("REAL");

                    b.Property<Guid>("SubId")
                        .HasColumnType("TEXT")
                        .HasColumnName("SubID");

                    b.Property<double?>("Temperature")
                        .HasColumnType("REAL");

                    b.HasKey("ReactorId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "SubId" }, "SubID")
                        .HasDatabaseName("SubID2");

                    b.ToTable("sub_reactor_data", (string)null);
                });

            modelBuilder.Entity("MyProjectTemplate.API.Models.SubAlarmsDatum", b =>
                {
                    b.HasOne("MyProjectTemplate.API.Models.SubDatum", "Sub")
                        .WithMany("SubAlarmsData")
                        .HasForeignKey("SubId")
                        .IsRequired()
                        .HasConstraintName("sub_alarms_data_ibfk_1");

                    b.Navigation("Sub");
                });

            modelBuilder.Entity("MyProjectTemplate.API.Models.SubControlDatum", b =>
                {
                    b.HasOne("MyProjectTemplate.API.Models.SubDatum", "Sub")
                        .WithMany("SubControlData")
                        .HasForeignKey("SubId")
                        .IsRequired()
                        .HasConstraintName("sub_control_data_ibfk_1");

                    b.Navigation("Sub");
                });

            modelBuilder.Entity("MyProjectTemplate.API.Models.SubLifeSupportDatum", b =>
                {
                    b.HasOne("MyProjectTemplate.API.Models.SubDatum", "Sub")
                        .WithMany("SubLifeSupportData")
                        .HasForeignKey("SubId")
                        .IsRequired()
                        .HasConstraintName("sub_life_support_data_ibfk_1");

                    b.Navigation("Sub");
                });

            modelBuilder.Entity("MyProjectTemplate.API.Models.SubLog", b =>
                {
                    b.HasOne("MyProjectTemplate.API.Models.SubDatum", "Sub")
                        .WithMany("SubLogs")
                        .HasForeignKey("SubId")
                        .IsRequired()
                        .HasConstraintName("sub_logs_ibfk_1");

                    b.Navigation("Sub");
                });

            modelBuilder.Entity("MyProjectTemplate.API.Models.SubPositionDatum", b =>
                {
                    b.HasOne("MyProjectTemplate.API.Models.SubDatum", "Sub")
                        .WithMany("SubPositionData")
                        .HasForeignKey("SubId")
                        .IsRequired()
                        .HasConstraintName("sub_position_data_ibfk_1");

                    b.Navigation("Sub");
                });

            modelBuilder.Entity("MyProjectTemplate.API.Models.SubReactorDatum", b =>
                {
                    b.HasOne("MyProjectTemplate.API.Models.SubDatum", "Sub")
                        .WithMany("SubReactorData")
                        .HasForeignKey("SubId")
                        .IsRequired()
                        .HasConstraintName("sub_reactor_data_ibfk_1");

                    b.Navigation("Sub");
                });

            modelBuilder.Entity("MyProjectTemplate.API.Models.SubDatum", b =>
                {
                    b.Navigation("SubAlarmsData");

                    b.Navigation("SubControlData");

                    b.Navigation("SubLifeSupportData");

                    b.Navigation("SubLogs");

                    b.Navigation("SubPositionData");

                    b.Navigation("SubReactorData");
                });
#pragma warning restore 612, 618
        }
    }
}
